export const TIMES = {
    COUNT_UP_DELAY: 0,
    COUNT_UP_DURATION: 2,
    SNACKBAR_DELAY: 4000,
    ERROR_MESSAGE_DURATION: 5000,
}

export const GAME = {
    ENERGY_CONSUPMTION: 15,
    ENERGY_RECHARGE: 10,
    CORRECT_ANSWER_POINTS: 500,
    WRONG_ANSWER_POINTS: 300,
    POINTS_PER_SECOND: 10,
    QUIZ_COMPLETE_THRESHOLD: 2200,
    TIME_PER_QUIZ: 3 * 60 * 1000, // 3 minutes
}