export const URLS = {
  HOME: "/",
  ABOUT: "/about",
  FAQ: "/faq",
  MEMBERSHIPS: "/memberships",
  CONTACT: "/contact",
  IMPRINT: "/imprint",
  PRIVACY: "/privacy",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  SIGNIN: "/auth/signin",
  SIGNUP: "/auth/signup",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
  DASHBOARD: "/dashboard",
  PROFILE: "/dashboard/profile",
  RANKINGS: "/dashboard/rankings",
  QUIZ_RANKING: "/dashboard/rankings/quiz-ranking/",
  API_URL: "https://philippmillner-api.dev",
  API_ENDPOINTS: {
    APP: {
      QUIZ_DATA: "/quiz-data",
      CONTACT: "/contact",
      USER: "/users",
      QUIZ_START: "/quizzes/start/",
      QUIZ_COMPLETE: "/quizzes/complete/",
      PERSONAL_RANKINGS: "/rankings/personal",
      OVERALL_QUIZ_RANKINGS: "/rankings/overall/",
      OVERALL_POINTS_RANKINGS: "/rankings/overall/points",
      OVERALL_PLAYTIME_RANKINGS: "/rankings/overall/playtime",
      OVERALL_MOST_PLAYED_QUIZZES_RANKINGS: "/rankings/overall/most-played-quizzes",
    },
    AUTH: {
      SIGNIN: "/auth/login",
      SIGNUP: "/auth/register",
      LOGOUT: "/auth/logout",
      SESSION: "/auth/session",
      FORGOT_PASSWORD: "/auth/forgot-password",
      RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
    },
  },
};
