export const URLS = {
  HOME: "/",
  ABOUT: "/about",
  FAQ: "/faq",
  MEMBERSHIPS: "/memberships",
  CONTACT: "/contact",
  IMPRINT: "/imprint",
  PRIVACY: "/privacy",
  TERMS_AND_CONDITIONS: "/terms-and-conditions",
  SIGNIN: "/auth/signin",
  SIGNUP: "/auth/signup",
  FORGOT_PASSWORD: "/auth/forgot-password",
  RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
  DASHBOARD: "/dashboard",
  QUIZ: "/dashboard/quiz",
  PROFILE: "/dashboard/profile/",
  RANKINGS: "/dashboard/rankings",
  MOST_POINTS_RANKING: "/dashboard/rankings/overall/points",
  MOST_PLAYTIME_RANKING: "/dashboard/rankings/overall/playtime",
  MOST_PLAYED_QUIZZES_RANKING: "/dashboard/rankings/overall/most-played-quizzes",
  QUIZ_RANKING: "/dashboard/rankings/quiz-ranking/",
  ADMIN_ROUTES: {
    DASHBOARD: "/dashboard/admin",
    USERS: "/dashboard/admin/users",
    QUIZZES: "/dashboard/admin/quizzes",
    CREATE_QUIZ: "/dashboard/admin/quizzes/create",
  },
  API_URL: import.meta.env.PROD ? "https://www.api.brain-blitz.com" : "http://localhost:3000",
  API_ENDPOINTS: {
    APP: {
      FORMS: {
        CONTACT: "/contact",
        REPORT: "/report",
      },
      HEALTH: "/health",
      QUIZ_DATA: "/quiz-data",
    },
    USER: {
      USERS: "/users",
    },
    QUIZ: {
      QUIZ_START: "/quizzes/start/",
      QUIZ_COMPLETE: "/quizzes/complete/",
      QUIZ: "/quizzes/",
    },
    RANKINGS: {
      PERSONAL: "/rankings/personal",
      SINGLE_QUIZ: "/rankings/overall/",
      OVERALL_POINTS: "/rankings/overall/points",
      OVERALL_PLAYTIME: "/rankings/overall/playtime",
      OVERALL_MOST_PLAYED_QUIZZES: "/rankings/overall/most-played-quizzes",
    },
    AUTH: {
      SIGN_IN: "/auth/login",
      SIGN_UP: "/auth/register",
      LOGOUT: "/auth/logout",
      SESSION: "/auth/session",
      FORGOT_PASSWORD: "/auth/forgot-password",
      RESEND_VERIFICATION_EMAIL: "/auth/resend-verification-email",
      RESET_PASSWORD: "/auth/reset-password",
    },
    ADMIN: {
      ALL_USERS: "/users/all",
      ALL_QUIZZES: "/quizzes/all",
    }
  },
};
